# Generated by Django 4.2 on 2023-04-27 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('location', models.CharField(default='unknown', max_length=100)),
                ('photo', models.ImageField(default='default.jpg', upload_to='dog_photos/')),
                ('is_adopted', models.BooleanField(default=False)),
                ('adoption_date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_phone_number', models.CharField(max_length=15)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('vet_name', models.CharField(max_length=100)),
                ('vet_phone_number', models.CharField(max_length=15)),
                ('reason', models.TextField()),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('r', 'Rejected')], default='p', max_length=1)),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.pet')),
            ],
        ),
    ]
